### ISSUE TITLE
Error 508 response

### ISSUE THREAD

**Issue by MrAmericanMike** [zehfernandes/get-vercel-source-code#9]
I haven't had luck with this script, I'm getting this error:

```
HTTPError: Response code 508 (Loop Detected)
    at Request.<anonymous> (file:///F:/VSCode/Vercel/get-vercel-source-code/node_modules/.pnpm/got@12.5.3/node_modules/got/dist/source/as-promise/index.js:86:42)
    at Object.onceWrapper (node:events:628:26)
    at Request.emit (node:events:525:35)
    at Request._onResponseBase (file:///F:/VSCode/Vercel/get-vercel-source-code/node_modules/.pnpm/got@12.5.3/node_modules/got/dist/source/core/index.js:726:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Request._onResponse (file:///F:/VSCode/Vercel/get-vercel-source-code/node_modules/.pnpm/got@12.5.3/node_modules/got/dist/source/core/index.js:765:13)
```

**Comment by MrAmericanMike** [comment]
Sorry I was using the wrong URL I missed the detail that it said "Deployment URL" I was using the app URL.

Thanks.
